-- Modified Knit Service Template
-- This is the structure that will be auto-generated by SuperbulletAI

-- File: ServerScriptService/ServiceName/init.lua

local Knit = require(game:GetService("ReplicatedStorage").Knit)

local ServiceName = Knit.CreateService({
    Name = "ServiceName",
    Client = {},
})

-- Components initialization
-- This pattern will be auto-generated for every service
ServiceName.Components = {}
for _, v in pairs(script:WaitForChild("Components", 10).Others:GetChildren()) do
    ServiceName.Components[v.Name] = require(v)
end

-- Load Get and Set components
ServiceName.GetComponent = require(script:WaitForChild("Components", 10)["Get()"])
ServiceName.SetComponent = require(script:WaitForChild("Components", 10)["Set()"])

-- Service initialization
function ServiceName:KnitStart()
    print("ServiceName started")
end

function ServiceName:KnitInit()
    print("ServiceName initialized")
end

return ServiceName
